# Site settings | 网站设置
title: DengWenbo's Homepage
SEOTitle: Homepage | Dengwenbo
# header-img: img/home-bg.jpg
header-img: img/R2.jpg
email: wenbodeng92@163.com
description: "Dengwenbo的主页"
keyword: "Dengwenbo, wenbo, 邓文博"
url: "http://dengwenbo.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Dengwenboo/dengwenbo.github.io.git" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "就算这样,也要笑着去努力啊!"
sidebar-avatar: /img/1.jpg    # 头像





# SNS settings | 社交网络设置
github_username: Dengwenboo
csdn_username: WilburTung




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: 823701c251bcf8601d2d                            #生成的clientID
  clientSecret: ef5c074d1cf46408aeca084004b370af140eccf1   #生成的clientSecret
  repo: dengwenbo.github.io    #仓库名称
  owner: Dengwenboo    # github用户名
  admin: Dengwenboo
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: f78c239215e48d4b39288e75443929cb


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub·RainbomSea",
        href: "http://RainbomSea.github.io"
    }
]
